FROM golang:alpine as build_sales-api

# maybe not needed anymore?
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /service
WORKDIR /service/app/services/sales-api

RUN	go build -ldflags "-X main.build=${BUILD_REF}" -o service main.go

FROM alpine

WORKDIR /service/salesapiweb
COPY --from=build_sales-api /service/app/services/sales-api/service .

ARG BUILD_REF
ARG BUILD_DATE

CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
  org.opencontainers.image.title="service-api" \
  org.opencontainers.image.revision="${BUILD_REF}" \
  org.opencontainers.image.author="wscnd" \
  org.opencontainers.image.vendor="wscnd"
