FROM golang:alpine as build_sales-api

# maybe not needed anymore?
# not binding any c libraries
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /service
WORKDIR /service/apps/server/sales

RUN	go build -ldflags "-X main.build=${BUILD_REF}" -o service main.go

###
FROM alpine:3.18
WORKDIR /service/salesapiweb

RUN addgroup -g 1000 -S sales && \
  adduser -u 1000 -h /service -G sales -S sales
# can probably embed the keys to the binary and use in memory instead of file
COPY --from=build_sales-api /service/zarf/keys/. /service/salesapiweb/zarf/keys/.
COPY --from=build_sales-api /service/apps/server/sales/service .

ARG BUILD_REF
ARG BUILD_DATE

CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
  org.opencontainers.image.title="sales-api" \
  org.opencontainers.image.source="https://github.com/wscnd/go-service-boilerplate/app/services/sales-api" \
  org.opencontainers.image.revision="${BUILD_REF}" \
  org.opencontainers.image.author="wscnd <72019998+wscnd@users.noreply.github.com>" \
  org.opencontainers.image.vendor="wscnd"