---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales

    spec:
      containers:
        - name: sales-api

          resources:
            requests:
              cpu: "500m" # 50ms/100ms on one core
              memory: "36Mi" # Needs to be benchmarked
            limits:
              cpu: "500m" # 50ms/100ms on one core
              memory: "36Mi" # Needs to be benchmarked

  replicas: 1
  strategy:
    type: Recreate
