apiVersion: v1
kind: Service
metadata:
  name: sales
  namespace: sales-system

spec:
  type: ClusterIP

  ports:
  - name: sales-api
    port: 3000
    targetPort: sales-api
  - name: sales-api-debug
    port: 4000
    targetPort: sales-api-debug