---
apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system
  labels:
    app: sales

spec:
  selector:
    matchLabels:
      app: sales

  template:
    metadata:
      labels:
        app: sales

    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: sales-api
          image: sales-image

          resources:
            requests:
              cpu: "250m" # 25ms/100ms on one core
              memory: "36Mi" # Needs to be benchmarked
            limits:
              cpu: "250m" # 25ms/100ms on one core
              memory: "36Mi" # Match the requests value

          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
---

