---
apiVersion: v1
kind: Namespace
metadata:
  name: service-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pod
  namespace: service-system

spec:
  selector:
    matchLabels:
      app: service

  template:
    metadata:
      labels:
        app: service

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: service-api
          image: ghcr.io/wscnd/service:0.1

          resources:
            requests:
              cpu: "1000m" # starts with one
              memory: "64Mi"
            limits:
              cpu: "2000m" # cap up to 2 full cores
              memory: "128Mi"

          env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
---

